### ISSUE TITLE
dupload crash on CentOS 6.9/386

### ISSUE THREAD

**Issue by watermint** [watermint/toolbox#21]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8049e0c]

goroutine 29 [running]:
sync/atomic.AddUint64(0x18b7a7e4, 0x1, 0x0, 0x8, 0x0)
	/usr/local/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/watermint/toolbox/vendor/github.com/watermint/bwlimit.(*Bwlimit).issue(0x18b7a7d0, 0x0, 0x0)
	/go/src/github.com/watermint/toolbox/vendor/github.com/watermint/bwlimit/bwlimit.go:96 +0xa0
github.com/watermint/toolbox/vendor/github.com/watermint/bwlimit.(*Bwlimit).Reader(0x18b7a7d0, 0x855e610, 0x18b5cec8, 0x0)
	/go/src/github.com/watermint/toolbox/vendor/github.com/watermint/bwlimit/bwlimit.go:114 +0x25
github.com/watermint/toolbox/service/upload.(*scanContext).uploadSingle(0x18b85660, 0x8563000, 0x18a3dcb0, 0x18b6d650, 0x25, 0x0, 0x0)
	/go/src/github.com/watermint/toolbox/service/upload/upload.go:183 +0x1f7
github.com/watermint/toolbox/service/upload.(*scanContext).upload(0x18b85660, 0x0, 0x0)
	/go/src/github.com/watermint/toolbox/service/upload/upload.go:150 +0x6c0
github.com/watermint/toolbox/service/upload.(*UploadContext).uploadRoutine(0x18816500)
	/go/src/github.com/watermint/toolbox/service/upload/upload.go:111 +0x5f
created by github.com/watermint/toolbox/service/upload.(*UploadContext).Upload
	/go/src/github.com/watermint/toolbox/service/upload/upload.go:66 +0x1a9
```

**Comment by watermint** [comment]
Fixed in https://github.com/watermint/bwlimit/issues/1
