### ISSUE TITLE
Fatal error on `team activities batch user`

### ISSUE THREAD

**Issue by watermint** [watermint/toolbox#293]
```
unexpected fault address 0x350a1044
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x350a1044 pc=0x784253]

goroutine 88 [running]:
runtime.throw(0xb362ad, 0x5)
        /usr/local/go/src/runtime/panic.go:774 +0x64 fp=0x1279eee0 sp=0x1279eecc pc=0x42d5a4
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_windows.go:236 +0x1ed fp=0x1279eef4 sp=0x1279eee0 pc=0x44036d
github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt.(*DB).meta(0x12476000, 0x41276)
        /go/src/github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt/db.go:901 +0x23 fp=0x1279ef0c sp=0x1279eef4 pc=0x784253
github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt.(*DB).hasSyncedFreelist(...)
        /go/src/github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt/db.go:323
github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt.(*Tx).rollback(0x13066d80)
        /go/src/github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt/tx.go:279 +0x69 fp=0x1279ef24 sp=0x1279ef0c pc=0x78d169
github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt.(*Tx).commitFreelist(0x13066d80, 0x41276, 0x0)
        /go/src/github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt/tx.go:231 +0x19f fp=0x1279ef60 sp=0x1279ef24 pc=0x78cf5f
github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt.(*Tx).Commit(0x13066d80, 0x0, 0x0)
        /go/src/github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt/tx.go:175 +0x429 fp=0x1279f004 sp=0x1279ef60 pc=0x78cbb9
github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt.(*DB).Update(0x12476000, 0x1279f058, 0x0, 0x0)
        /go/src/github.com/watermint/toolbox/vendor/github.com/etcd-io/bbolt/db.go:701 +0xd1 fp=0x1279f048 sp=0x1279f004 pc=0x7838a1
github.com/watermint/toolbox/infra/kvs/kv_storage_impl.(*bboltWrapper).Update(0x1245d6c0, 0x130c13a0, 0x0, 0x0)
        /go/src/github.com/watermint/toolbox/infra/kvs/kv_storage_impl/storage.go:44 +0x5a fp=0x1279f068 sp=0x1279f048 pc=0x793b0a
github.com/watermint/toolbox/recipe/team/activity/batch.(*UserWorker).Exec.func1(0x125d6b40, 0xa7c560, 0x125d6b40)
        /go/src/github.com/watermint/toolbox/recipe/team/activity/batch/user.go:64 +0x7d fp=0x1279f088 sp=0x1279f068 pc=0x99ca4d
```

**Comment by watermint** [comment]
Similar issue: 
https://github.com/etcd-io/bbolt/issues/194

**Comment by watermint** [comment]
The issue happens on the database exceeds 2^30 bytes (1GB).
https://github.com/etcd-io/bbolt/blob/master/db.go#L17

**Comment by watermint** [comment]
The error on Win 10 32bit environment:

```
ERROR   Invalid argument, or unable to spin up  {"key": "EventCache", "error": "Mmap value log file. Path=C:\\Users\\USER\\.toolbox\\jobs\\20200225-104937.345\\kvs\\EventCache\\000000.vlog. Error=MapViewOfFile: The parameter is incorrect."}ERROR   Recipe failed with an error     {"error": "Mmap value log file. Path=C:\\Users\\USER\\.toolbox\\jobs\\20200225-104937.345\\kvs\\EventCache\\000000.vlog. Error=MapViewOfFile: The parameter is incorrect."}処理がエラーにより終了しました: Mmap value log file. Path=C:\Users\USER\.toolbox\jobs\20200225-104937.345\kvs\EventCache\000000.vlog. Error=MapViewOfFile: The parameter is incorrect.
```

The issue look like very similar to https://github.com/dgraph-io/badger/issues/1072

**Comment by watermint** [comment]
After adding below option, the issue solved. 
```
	if app.IsWindows() && runtime.GOARCH == "386" {
		opts.ValueLogFileSize = 2 << 24
	}
```

Hypothesis: default 2^30 might inappropriate for 32 bit environment. 
https://github.com/dgraph-io/badger/blob/master/options.go#L127

**Comment by watermint** [comment]
OOM in both 32/64 bit Win 10

## Win 10 32 bit

```
runtime: out of memory: cannot allocate 67117056-byte block (494272512 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0xc8226e, 0xd)
        /usr/local/go/src/runtime/panic.go:774 +0x64
runtime.largeAlloc(0x40006d5, 0x12430101, 0x37f8d9c0)
        /usr/local/go/src/runtime/malloc.go:1140 +0x108
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:1033 +0x39
runtime.systemstack(0x455802)
        /usr/local/go/src/runtime/asm_386.s:399 +0x53
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1146

goroutine 60 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_386.s:360 fp=0x124f95f8 sp=0x124f95f4 pc=0x4558b0
runtime.mallocgc(0x40006d5, 0xb85280, 0x1, 0x1)
        /usr/local/go/src/runtime/malloc.go:1032 +0x684 fp=0x124f964c sp=0x124f95f8 pc=0x40acf4
runtime.makeslice(0xb85280, 0x40006d5, 0x40006d5, 0x19009aa0)
        /usr/local/go/src/runtime/slice.go:49 +0x4f fp=0x124f9660 sp=0x124f964c pc=0x44082f
bytes.makeSlice(0x40006d5, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:229 +0x69 fp=0x124f9694 sp=0x124f9660 pc=0x4f4259
bytes.(*Buffer).grow(0x1346d7c0, 0x27, 0xa)
        /usr/local/go/src/bytes/buffer.go:142 +0x11c fp=0x124f96bc sp=0x124f9694 pc=0x4f3cac
```

## Win 10 64bit

```
WARN    writeRequests: Mmap value log file. Path=C:\Users\USER\.toolbox\jobs\20200225-120725.068\kvs\EventCache\000029.vlog. Error=MapViewOfFile: Not enough memory resources are available to process this command.        {"name": "EventCache", "path": "C:\\Users\\USER\\.toolbox\\jobs\\20200225-120725.068\\kvs\\EventCache", "level": "error"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x24 pc=0x84f3dc]

goroutine 1881702 [running]:
github.com/dgraph-io/badger.(*valueLog).write(0x126d02b8, 0x16a63ec0, 0x2, 0xa, 0x0, 0x0)
        /go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/value.go:1037 +0x1cc
github.com/dgraph-io/badger.(*DB).writeRequests(0x126d01e0, 0x16a63ec0, 0x2, 0xa, 0x43482e, 0xd51de0)
        /go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/db.go:619 +0xc9
github.com/dgraph-io/badger.(*DB).doWrites.func1(0x16a63ec0, 0x2, 0xa)
        /go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/db.go:692 +0x47
created by github.com/dgraph-io/badger.(*DB).doWrites
        /go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/db.go:741 +0x286
```
