### ISSUE TITLE
toolbox crashed 

### ISSUE THREAD

**Issue by watermint** [watermint/toolbox#411]
**Describe the bug**
Crash

**To Reproduce**
run command

**Screenshots, or log snippets**
```
goroutine 443 [running]:
github.com/mattn/go-colorable.(*Writer).Write(0xc000080460, 0xc008b21400, 0x142, 0x200, 0x1b46220, 0x10df820, 0xc008
40)
        /go/pkg/mod/github.com/mattn/go-colorable@v0.1.6/colorable_windows.go:504 +0x345f
github.com/watermint/toolbox/essentials/io/es_stdout.syncOut.Write(...)
        /go/src/github.com/watermint/toolbox/essentials/io/es_stdout/defaultout.go:84
fmt.Fprintf(0x29978030, 0xc0002ebae0, 0x110a7e8, 0xb, 0xc00022d3d8, 0x2, 0x2, 0xc00022d3f0, 0x7e2384, 0xc000b94480)
        /usr/local/go/src/fmt/print.go:205 +0xac
github.com/watermint/toolbox/essentials/terminal/es_color.Colorf(0x29978030, 0xc0002ebae0, 0x25, 0x0, 0xc009fa0a00,
9, 0x0, 0x0, 0x0)
        /go/src/github.com/watermint/toolbox/essentials/terminal/es_color/color.go:35 +0x23b
github.com/watermint/toolbox/essentials/terminal/es_color.Colorfln(0x29978030, 0xc0002ebae0, 0x25, 0xc009fa0a00, 0xc
a0a00, 0x139, 0x0, 0x0, 0x0)
        /go/src/github.com/watermint/toolbox/essentials/terminal/es_color/color.go:43 +0x91
github.com/watermint/toolbox/infra/ui/app_ui.conImpl.Info(0x13c9040, 0xc000ab3420, 0x29978030, 0xc0002ebae0, 0x13c8d
0xc000ab3460, 0x13c8fc0, 0xc009f90cc0)
        /go/src/github.com/watermint/toolbox/infra/ui/app_ui/console.go:81 +0xa1
github.com/watermint/toolbox/infra/ui/app_ui.proxyImpl.Info.func1()
        /go/src/github.com/watermint/toolbox/infra/ui/app_ui/proxy.go:72 +0x48
github.com/watermint/toolbox/infra/ui/app_ui.proxyImpl.withMsg(0x1b03232, 0x1, 0x13d3b80, 0xc000ab34c0, 0x13e1ee0, 0
0b81560, 0x11025d8, 0x4, 0x13c8fc0, 0xc009f90cc0, ...)
        /go/src/github.com/watermint/toolbox/infra/ui/app_ui/proxy.go:55 +0x59a
github.com/watermint/toolbox/infra/ui/app_ui.proxyImpl.Info(0x1b03232, 0x1, 0x13d3b80, 0xc000ab34c0, 0x13e1ee0, 0xc0
1560, 0x13c8fc0, 0xc009f90cc0)
        /go/src/github.com/watermint/toolbox/infra/ui/app_ui/proxy.go:71 +0x106
github.com/watermint/toolbox/ingredient/file.(*UploadWorker).Exec(0xc009a3cc60, 0x110704d, 0x8)
        /go/src/github.com/watermint/toolbox/ingredient/file/upload_worker.go:94 +0xe55
github.com/watermint/toolbox/infra/recipe/rc_worker_impl.(*Queue).dequeue(0xc000081ea0)
        /go/src/github.com/watermint/toolbox/infra/recipe/rc_worker_impl/worker.go:40 +0x4dc
created by github.com/watermint/toolbox/infra/recipe/rc_worker_impl.(*Queue).Enqueue
        /go/src/github.com/watermint/toolbox/infra/recipe/rc_worker_impl/worker.go:72 +0x654
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - toolbox Version 71.4.504

**Additional context**

**Comment by watermint** [comment]
Try version up go-colorable to v1.7 due to an issue https://github.com/mattn/go-colorable/issues/48
