### ISSUE TITLE
Windows build broken

### ISSUE THREAD

**Issue by watermint** [watermint/toolbox#514]
```
ERROR   No resources loaded     {"error": "open messages\\messages.json: file does not exist"}
panic: At least one message resource required [recovered]
        panic: At least one message resource required

goroutine 1 [running]:
main.run.func1()
        /go/src/github.com/watermint/toolbox/tbx.go:22 +0x59
panic(0x18ae240, 0x1c0b468)
        /usr/local/go/src/runtime/panic.go:965 +0x153
github.com/watermint/toolbox/infra/ui/app_msg_container_impl.NewContainer(0x19615c0, 0x1c2e5a8)
        /go/src/github.com/watermint/toolbox/infra/ui/app_msg_container_impl/container.go:26 +0x43b
github.com/watermint/toolbox/infra/control/app_bootstrap.bsImpl.bootUI(0x0, 0x1f)
        /go/src/github.com/watermint/toolbox/infra/control/app_bootstrap/bootstrap.go:245 +0x50
github.com/watermint/toolbox/infra/control/app_bootstrap.(*bsImpl).Parse(0x13a63f9f, 0x13806130, 0x0, 0x0, 0x138042d0, 0x1, 0x0)
        /go/src/github.com/watermint/toolbox/infra/control/app_bootstrap/bootstrap.go:270 +0x27
main.run(0x13806130, 0x1, 0x1, 0x13834200)
        /go/src/github.com/watermint/toolbox/tbx.go:35 +0x14c
main.main()
        /go/src/github.com/watermint/toolbox/tbx.go:39 +0x3c
```

**Comment by watermint** [comment]
https://github.com/golang/go/issues/44305
